### PR TITLE
Fixing notebook/lab installation bug

### PR DESCRIPTION
**Pull request by cjachekang**
Previously, after running `jupyter labextension install luxwidget` for JupyterLab if we also want to enable Jupyter notebook via `jupyter nbextension install` and `enable`, it errors on `static/` directory not found.
This PR fixes this issue by including the static/ directory when installing the npm package. These commands now work.
```bash
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install luxwidget

jupyter nbextension install --py --user luxwidget
jupyter nbextension enable --py --user luxwidget
```

### CODE REVIEW

**Comment by dorisjlee** [comment]
Thanks @cjachekang! I was able to test this by pulling in the latest code from this PR: 
```bash
cd lux-widget
git checkout -b cjachekang-master master
git pull https://github.com/cjachekang/lux-widget.git master
```
Then doing:
```bash
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install .

jupyter nbextension install --py --user luxwidget
jupyter nbextension enable --py --user luxwidget
```
I couldn't do `jupyter labextension install luxwidget` since it hasn't been uploaded to NPM yet (@cjachekang: can you verify that this is expected?) The widget is correctly rendering in both jupyter notebook and jupyter lab even after the last two `nbextension` commands. 

@jinimukh: Could you also test this on your laptop to see if you can get the widget to work on both notebook and lab?

**Review by dorisjlee — APPROVED** [review]

**Comment by cjachekang** [comment]
Yes - to simulate the `jupyter labextension install luxwidget` command, you can run `npm pack` on the local luxwidget directory and run `jupyter labextension install tarball_name` on the tarball that is generated. I believe that is the same as if installing from npm.

**Comment by dorisjlee** [comment]
Ok great, I've followed those instructions again with the `npm pack` and it seems to be working. We can merge it in after @jinimukh can verify it on her end too.

**Review by jinimukh — APPROVED** [review]
Looks good -- just remove the commented code if you can!

**Comment by jinimukh** [comment]
Also, does any documentation need to be updated?

**Review by dorisjlee — APPROVED** [review]

**Pull request merged**
