### PR TITLE
Expanded Long Description Box

### PR DESCRIPTION
**Pull request by jerrysong1324**
Followup to #67 
## Changed 
- Synced long description info panel state across different tabs
- Changed span of info panel to be across entire widget as opposed to just on tab
- Reformatted w/ black
- Rebuilt and pushed
## Screenshots
Screen Shot 2021-03-03 at 12 28 04 AM
Screen Shot 2021-03-03 at 12 27 43 AM

### CODE REVIEW

**Review by dorisjlee — APPROVED** [review]

**Comment by dorisjlee** [comment]
Hey @jerrysong1324, The changes here looks good! I'm also assigning @cjachekang as a reviewer. 
@cjachekang : Let us know if it makes more sense to merge this issue in first or #71 for preventing merge conflicts!

**Comment by cjachekang** [comment]
@dorisjlee this can be merged in first - also, are we always merging in the index.js/index.js.map files?

**Review by cjachekang — APPROVED** [review]

**Comment by jerrysong1324** [comment]
My understanding is that we are merging in the index.js/index.js.map files right? I thought I asked Doris before and that's what she said.

**Comment by dorisjlee** [comment]
Yeah we are merging the index.js files since these compiled files are what the nbextension uses for non-dev installs (e.g. binder and PyPI releases).

**Pull request merged**
