### PR TITLE
Adding Long Descriptions 

### PR DESCRIPTION
**Pull request by jerrysong1324**
In response to Lux Issue #216
Related to Lux PR 244
- Added long descriptions to chart gallery which appear during press of info button
- Made decision to move long description to right below the short description as opposed to below whole widget in order to not be confused with error messages
- Created new CSS classes to style the long description msg (can consider merging with warning message CSS classes)
- Open to other CSS / appearance suggestions
- Fixed some style in other files

### CODE REVIEW

**Comment by dorisjlee** [comment]
Thanks @jerrysong1324! The logic largely looks good. 
I've attached some possible UI improvements:
- increase infoBtn so that it is slightly larger and with a bit more spacing with respect to the main text.
- allow clicking on infoBtn a second time to close the message. That way we can remove the closeBtn on the top right of the message box.
- Currently, there seems to be some vertical space between the text and the visualizations (see red box). It might help to shrink that and keep it more compact. 
Screen Shot 2021-01-26 at 10 22 48 PM
- The message box feels like it is missing something aesthetically. We might want to check out better styling for modal windows to improve the message box (background color, border). A pop-up window might be better spacing-wise so that we can be more elaborate with the action description (e.g., embed toy example images in the description). 
I'll let @cjachekang also chime in on the message box design especially as it relates to the placement of the message box.

**Comment by cjachekang** [comment]
The message box doesn't show up for me.
image

I think it would be a little bit more intuitive to have the close button on the message since that is what people would be used to. I think what would be nice in terms of UI is if we hovered over the button instead of clicking.

**Comment by jerrysong1324** [comment]
@cjachekang Thanks for the comments on UI design. I think your descriptions are not appearing because you might not have the lux backend up to date with my fork. Look at this PR to get the info you need: https://github.com/lux-org/lux/pull/244

I would actually argue against a popup/hover design. I think that popups are typically used to explain the functionality of a certain button (eg. click me to print, click me to delete, etc.) and I think this expand and collapse design is better for additional info. @dorisjlee What are your thoughts on this? I'd be happy to make changes if any of y'all feel differently. We can chat during Lux meeting Wed as well. 

Will be working on aesthetic changes (enlarging info btn, spacing, etc.) I like the idea of the info button and close button closing the expander.

**Comment by cjachekang** [comment]
Ah that fixed it, now it works fine. Also, that makes sense, I think the current way is fine as well.

**Review by cjachekang — APPROVED** [review]

**Comment by jerrysong1324** [comment]
Made modifications to UI based on suggestions from @dorisjlee @cjachekang and @micahtyong 

Let me know what y'all think! 

Screen Shot 2021-02-15 at 12 00 02 AM

**Comment by dorisjlee** [comment]
Thanks @jerrysong1324! This looks good, two minor aesthetics suggestions: 
- Can we replace the info button with [this](https://fontawesome.com/icons/info-circle?style=solid) instead of the exclamation mark? 
- It might help to add a header description (larger bold title?) that clarifies that the blue area is "Description of {action name}" and that the yellow area is "Warnings". 
- For the content text, we would also want to align the starting point of the textual description by indenting appropriately so that the style looks consistent across the blue and yellow areas.
image

**Comment by jerrysong1324** [comment]
I made the changes to the button and margin, but I'm not sure a title/header is a good idea. It might take up a lot of unnecessary space, especially since it is pretty rare that both these panels will be open simultaneously. Furthermore, the panel only appears after clicking the button, so I think hopefully, it makes sense to users. Let me know if you still want it in. It's pretty easy to add.

**Comment by dorisjlee** [comment]
Thanks @jerrysong1324, the new changes look good. You make a valid point about the header taking up space, so let's leave this out for now. 

- Even though the description is action-specific, I'm wondering if we should extend the div to span over the Current Vis, since it looks pretty awkward with the blue and yellow spanning different widths.
image
- Another thing that I noticed is that for each action, I need to toggle the info button on every single tab to open the description, and then close each one individually. Can we use the info button open the info box on all tabs, and have the close button close all the info box on all tabs? This is similar behavior as the warning box, and will save users a lot of time having to go back and forth between the tabs and button. 
Feb-16-2021 12-43-40
- For both the info and warning box, can we just use the same button for opening/closing the box and remove the close button altogether? (i.e., single-clicking on the info icon to open,  double-clicking to close)  This will make opening/closing the tab much easier to do and faster.

**Comment by jerrysong1324** [comment]
Addressed 3rd bullet point, made the buttons toggle rather than strictly open. Kept the 'x' button on the panels so users could close.

**Comment by dorisjlee** [comment]
Thanks @jerrysong1324 !

**Pull request merged**
